//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExternalServiceCalls.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="portalquery.just.ro", ConfigurationName="ServiceReference2.QuerySoap")]
    public interface QuerySoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace portalquery.just.ro is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="portalquery.just.ro/HelloWorld", ReplyAction="*")]
        ExternalServiceCalls.ServiceReference2.HelloWorldResponse HelloWorld(ExternalServiceCalls.ServiceReference2.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="portalquery.just.ro/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<ExternalServiceCalls.ServiceReference2.HelloWorldResponse> HelloWorldAsync(ExternalServiceCalls.ServiceReference2.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name numarDosar from namespace portalquery.just.ro is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="portalquery.just.ro/CautareDosare", ReplyAction="*")]
        ExternalServiceCalls.ServiceReference2.CautareDosareResponse CautareDosare(ExternalServiceCalls.ServiceReference2.CautareDosareRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="portalquery.just.ro/CautareDosare", ReplyAction="*")]
        System.Threading.Tasks.Task<ExternalServiceCalls.ServiceReference2.CautareDosareResponse> CautareDosareAsync(ExternalServiceCalls.ServiceReference2.CautareDosareRequest request);
        
        // CODEGEN: Generating message contract since element name numarDosar from namespace portalquery.just.ro is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="portalquery.just.ro/CautareDosare2", ReplyAction="*")]
        ExternalServiceCalls.ServiceReference2.CautareDosare2Response CautareDosare2(ExternalServiceCalls.ServiceReference2.CautareDosare2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="portalquery.just.ro/CautareDosare2", ReplyAction="*")]
        System.Threading.Tasks.Task<ExternalServiceCalls.ServiceReference2.CautareDosare2Response> CautareDosare2Async(ExternalServiceCalls.ServiceReference2.CautareDosare2Request request);
        
        // CODEGEN: Generating message contract since element name CautareSedinteResult from namespace portalquery.just.ro is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="portalquery.just.ro/CautareSedinte", ReplyAction="*")]
        ExternalServiceCalls.ServiceReference2.CautareSedinteResponse CautareSedinte(ExternalServiceCalls.ServiceReference2.CautareSedinteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="portalquery.just.ro/CautareSedinte", ReplyAction="*")]
        System.Threading.Tasks.Task<ExternalServiceCalls.ServiceReference2.CautareSedinteResponse> CautareSedinteAsync(ExternalServiceCalls.ServiceReference2.CautareSedinteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="portalquery.just.ro", Order=0)]
        public ExternalServiceCalls.ServiceReference2.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ExternalServiceCalls.ServiceReference2.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="portalquery.just.ro", Order=0)]
        public ExternalServiceCalls.ServiceReference2.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ExternalServiceCalls.ServiceReference2.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="portalquery.just.ro")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CautareDosareRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CautareDosare", Namespace="portalquery.just.ro", Order=0)]
        public ExternalServiceCalls.ServiceReference2.CautareDosareRequestBody Body;
        
        public CautareDosareRequest() {
        }
        
        public CautareDosareRequest(ExternalServiceCalls.ServiceReference2.CautareDosareRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="portalquery.just.ro")]
    public partial class CautareDosareRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string numarDosar;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string obiectDosar;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string numeParte;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<socisaV2.PortalWS.Institutie> institutie;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.Nullable<System.DateTime> dataStart;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.Nullable<System.DateTime> dataStop;
        
        public CautareDosareRequestBody() {
        }
        
        public CautareDosareRequestBody(string numarDosar, string obiectDosar, string numeParte, System.Nullable<socisaV2.PortalWS.Institutie> institutie, System.Nullable<System.DateTime> dataStart, System.Nullable<System.DateTime> dataStop) {
            this.numarDosar = numarDosar;
            this.obiectDosar = obiectDosar;
            this.numeParte = numeParte;
            this.institutie = institutie;
            this.dataStart = dataStart;
            this.dataStop = dataStop;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CautareDosareResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CautareDosareResponse", Namespace="portalquery.just.ro", Order=0)]
        public ExternalServiceCalls.ServiceReference2.CautareDosareResponseBody Body;
        
        public CautareDosareResponse() {
        }
        
        public CautareDosareResponse(ExternalServiceCalls.ServiceReference2.CautareDosareResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="portalquery.just.ro")]
    public partial class CautareDosareResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public socisaV2.PortalWS.Dosar[] CautareDosareResult;
        
        public CautareDosareResponseBody() {
        }
        
        public CautareDosareResponseBody(socisaV2.PortalWS.Dosar[] CautareDosareResult) {
            this.CautareDosareResult = CautareDosareResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CautareDosare2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CautareDosare2", Namespace="portalquery.just.ro", Order=0)]
        public ExternalServiceCalls.ServiceReference2.CautareDosare2RequestBody Body;
        
        public CautareDosare2Request() {
        }
        
        public CautareDosare2Request(ExternalServiceCalls.ServiceReference2.CautareDosare2RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="portalquery.just.ro")]
    public partial class CautareDosare2RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string numarDosar;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string obiectDosar;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string numeParte;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<socisaV2.PortalWS.Institutie> institutie;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.Nullable<System.DateTime> dataStart;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.Nullable<System.DateTime> dataStop;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public System.Nullable<System.DateTime> dataUltimaModificareStart;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public System.Nullable<System.DateTime> dataUltimaModificareStop;
        
        public CautareDosare2RequestBody() {
        }
        
        public CautareDosare2RequestBody(string numarDosar, string obiectDosar, string numeParte, System.Nullable<socisaV2.PortalWS.Institutie> institutie, System.Nullable<System.DateTime> dataStart, System.Nullable<System.DateTime> dataStop, System.Nullable<System.DateTime> dataUltimaModificareStart, System.Nullable<System.DateTime> dataUltimaModificareStop) {
            this.numarDosar = numarDosar;
            this.obiectDosar = obiectDosar;
            this.numeParte = numeParte;
            this.institutie = institutie;
            this.dataStart = dataStart;
            this.dataStop = dataStop;
            this.dataUltimaModificareStart = dataUltimaModificareStart;
            this.dataUltimaModificareStop = dataUltimaModificareStop;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CautareDosare2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CautareDosare2Response", Namespace="portalquery.just.ro", Order=0)]
        public ExternalServiceCalls.ServiceReference2.CautareDosare2ResponseBody Body;
        
        public CautareDosare2Response() {
        }
        
        public CautareDosare2Response(ExternalServiceCalls.ServiceReference2.CautareDosare2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="portalquery.just.ro")]
    public partial class CautareDosare2ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public socisaV2.PortalWS.Dosar[] CautareDosare2Result;
        
        public CautareDosare2ResponseBody() {
        }
        
        public CautareDosare2ResponseBody(socisaV2.PortalWS.Dosar[] CautareDosare2Result) {
            this.CautareDosare2Result = CautareDosare2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CautareSedinteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CautareSedinte", Namespace="portalquery.just.ro", Order=0)]
        public ExternalServiceCalls.ServiceReference2.CautareSedinteRequestBody Body;
        
        public CautareSedinteRequest() {
        }
        
        public CautareSedinteRequest(ExternalServiceCalls.ServiceReference2.CautareSedinteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="portalquery.just.ro")]
    public partial class CautareSedinteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime dataSedinta;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public socisaV2.PortalWS.Institutie institutie;
        
        public CautareSedinteRequestBody() {
        }
        
        public CautareSedinteRequestBody(System.DateTime dataSedinta, socisaV2.PortalWS.Institutie institutie) {
            this.dataSedinta = dataSedinta;
            this.institutie = institutie;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CautareSedinteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CautareSedinteResponse", Namespace="portalquery.just.ro", Order=0)]
        public ExternalServiceCalls.ServiceReference2.CautareSedinteResponseBody Body;
        
        public CautareSedinteResponse() {
        }
        
        public CautareSedinteResponse(ExternalServiceCalls.ServiceReference2.CautareSedinteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="portalquery.just.ro")]
    public partial class CautareSedinteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public socisaV2.PortalWS.Sedinta[] CautareSedinteResult;
        
        public CautareSedinteResponseBody() {
        }
        
        public CautareSedinteResponseBody(socisaV2.PortalWS.Sedinta[] CautareSedinteResult) {
            this.CautareSedinteResult = CautareSedinteResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface QuerySoapChannel : ExternalServiceCalls.ServiceReference2.QuerySoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QuerySoapClient : System.ServiceModel.ClientBase<ExternalServiceCalls.ServiceReference2.QuerySoap>, ExternalServiceCalls.ServiceReference2.QuerySoap {
        
        public QuerySoapClient() {
        }
        
        public QuerySoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QuerySoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QuerySoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QuerySoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ExternalServiceCalls.ServiceReference2.HelloWorldResponse ExternalServiceCalls.ServiceReference2.QuerySoap.HelloWorld(ExternalServiceCalls.ServiceReference2.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ExternalServiceCalls.ServiceReference2.HelloWorldRequest inValue = new ExternalServiceCalls.ServiceReference2.HelloWorldRequest();
            inValue.Body = new ExternalServiceCalls.ServiceReference2.HelloWorldRequestBody();
            ExternalServiceCalls.ServiceReference2.HelloWorldResponse retVal = ((ExternalServiceCalls.ServiceReference2.QuerySoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ExternalServiceCalls.ServiceReference2.HelloWorldResponse> ExternalServiceCalls.ServiceReference2.QuerySoap.HelloWorldAsync(ExternalServiceCalls.ServiceReference2.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ExternalServiceCalls.ServiceReference2.HelloWorldResponse> HelloWorldAsync() {
            ExternalServiceCalls.ServiceReference2.HelloWorldRequest inValue = new ExternalServiceCalls.ServiceReference2.HelloWorldRequest();
            inValue.Body = new ExternalServiceCalls.ServiceReference2.HelloWorldRequestBody();
            return ((ExternalServiceCalls.ServiceReference2.QuerySoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ExternalServiceCalls.ServiceReference2.CautareDosareResponse ExternalServiceCalls.ServiceReference2.QuerySoap.CautareDosare(ExternalServiceCalls.ServiceReference2.CautareDosareRequest request) {
            return base.Channel.CautareDosare(request);
        }
        
        public socisaV2.PortalWS.Dosar[] CautareDosare(string numarDosar, string obiectDosar, string numeParte, System.Nullable<socisaV2.PortalWS.Institutie> institutie, System.Nullable<System.DateTime> dataStart, System.Nullable<System.DateTime> dataStop) {
            ExternalServiceCalls.ServiceReference2.CautareDosareRequest inValue = new ExternalServiceCalls.ServiceReference2.CautareDosareRequest();
            inValue.Body = new ExternalServiceCalls.ServiceReference2.CautareDosareRequestBody();
            inValue.Body.numarDosar = numarDosar;
            inValue.Body.obiectDosar = obiectDosar;
            inValue.Body.numeParte = numeParte;
            inValue.Body.institutie = institutie;
            inValue.Body.dataStart = dataStart;
            inValue.Body.dataStop = dataStop;
            ExternalServiceCalls.ServiceReference2.CautareDosareResponse retVal = ((ExternalServiceCalls.ServiceReference2.QuerySoap)(this)).CautareDosare(inValue);
            return retVal.Body.CautareDosareResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ExternalServiceCalls.ServiceReference2.CautareDosareResponse> ExternalServiceCalls.ServiceReference2.QuerySoap.CautareDosareAsync(ExternalServiceCalls.ServiceReference2.CautareDosareRequest request) {
            return base.Channel.CautareDosareAsync(request);
        }
        
        public System.Threading.Tasks.Task<ExternalServiceCalls.ServiceReference2.CautareDosareResponse> CautareDosareAsync(string numarDosar, string obiectDosar, string numeParte, System.Nullable<socisaV2.PortalWS.Institutie> institutie, System.Nullable<System.DateTime> dataStart, System.Nullable<System.DateTime> dataStop) {
            ExternalServiceCalls.ServiceReference2.CautareDosareRequest inValue = new ExternalServiceCalls.ServiceReference2.CautareDosareRequest();
            inValue.Body = new ExternalServiceCalls.ServiceReference2.CautareDosareRequestBody();
            inValue.Body.numarDosar = numarDosar;
            inValue.Body.obiectDosar = obiectDosar;
            inValue.Body.numeParte = numeParte;
            inValue.Body.institutie = institutie;
            inValue.Body.dataStart = dataStart;
            inValue.Body.dataStop = dataStop;
            return ((ExternalServiceCalls.ServiceReference2.QuerySoap)(this)).CautareDosareAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ExternalServiceCalls.ServiceReference2.CautareDosare2Response ExternalServiceCalls.ServiceReference2.QuerySoap.CautareDosare2(ExternalServiceCalls.ServiceReference2.CautareDosare2Request request) {
            return base.Channel.CautareDosare2(request);
        }
        
        public socisaV2.PortalWS.Dosar[] CautareDosare2(string numarDosar, string obiectDosar, string numeParte, System.Nullable<socisaV2.PortalWS.Institutie> institutie, System.Nullable<System.DateTime> dataStart, System.Nullable<System.DateTime> dataStop, System.Nullable<System.DateTime> dataUltimaModificareStart, System.Nullable<System.DateTime> dataUltimaModificareStop) {
            ExternalServiceCalls.ServiceReference2.CautareDosare2Request inValue = new ExternalServiceCalls.ServiceReference2.CautareDosare2Request();
            inValue.Body = new ExternalServiceCalls.ServiceReference2.CautareDosare2RequestBody();
            inValue.Body.numarDosar = numarDosar;
            inValue.Body.obiectDosar = obiectDosar;
            inValue.Body.numeParte = numeParte;
            inValue.Body.institutie = institutie;
            inValue.Body.dataStart = dataStart;
            inValue.Body.dataStop = dataStop;
            inValue.Body.dataUltimaModificareStart = dataUltimaModificareStart;
            inValue.Body.dataUltimaModificareStop = dataUltimaModificareStop;
            ExternalServiceCalls.ServiceReference2.CautareDosare2Response retVal = ((ExternalServiceCalls.ServiceReference2.QuerySoap)(this)).CautareDosare2(inValue);
            return retVal.Body.CautareDosare2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ExternalServiceCalls.ServiceReference2.CautareDosare2Response> ExternalServiceCalls.ServiceReference2.QuerySoap.CautareDosare2Async(ExternalServiceCalls.ServiceReference2.CautareDosare2Request request) {
            return base.Channel.CautareDosare2Async(request);
        }
        
        public System.Threading.Tasks.Task<ExternalServiceCalls.ServiceReference2.CautareDosare2Response> CautareDosare2Async(string numarDosar, string obiectDosar, string numeParte, System.Nullable<socisaV2.PortalWS.Institutie> institutie, System.Nullable<System.DateTime> dataStart, System.Nullable<System.DateTime> dataStop, System.Nullable<System.DateTime> dataUltimaModificareStart, System.Nullable<System.DateTime> dataUltimaModificareStop) {
            ExternalServiceCalls.ServiceReference2.CautareDosare2Request inValue = new ExternalServiceCalls.ServiceReference2.CautareDosare2Request();
            inValue.Body = new ExternalServiceCalls.ServiceReference2.CautareDosare2RequestBody();
            inValue.Body.numarDosar = numarDosar;
            inValue.Body.obiectDosar = obiectDosar;
            inValue.Body.numeParte = numeParte;
            inValue.Body.institutie = institutie;
            inValue.Body.dataStart = dataStart;
            inValue.Body.dataStop = dataStop;
            inValue.Body.dataUltimaModificareStart = dataUltimaModificareStart;
            inValue.Body.dataUltimaModificareStop = dataUltimaModificareStop;
            return ((ExternalServiceCalls.ServiceReference2.QuerySoap)(this)).CautareDosare2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ExternalServiceCalls.ServiceReference2.CautareSedinteResponse ExternalServiceCalls.ServiceReference2.QuerySoap.CautareSedinte(ExternalServiceCalls.ServiceReference2.CautareSedinteRequest request) {
            return base.Channel.CautareSedinte(request);
        }
        
        public socisaV2.PortalWS.Sedinta[] CautareSedinte(System.DateTime dataSedinta, socisaV2.PortalWS.Institutie institutie) {
            ExternalServiceCalls.ServiceReference2.CautareSedinteRequest inValue = new ExternalServiceCalls.ServiceReference2.CautareSedinteRequest();
            inValue.Body = new ExternalServiceCalls.ServiceReference2.CautareSedinteRequestBody();
            inValue.Body.dataSedinta = dataSedinta;
            inValue.Body.institutie = institutie;
            ExternalServiceCalls.ServiceReference2.CautareSedinteResponse retVal = ((ExternalServiceCalls.ServiceReference2.QuerySoap)(this)).CautareSedinte(inValue);
            return retVal.Body.CautareSedinteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ExternalServiceCalls.ServiceReference2.CautareSedinteResponse> ExternalServiceCalls.ServiceReference2.QuerySoap.CautareSedinteAsync(ExternalServiceCalls.ServiceReference2.CautareSedinteRequest request) {
            return base.Channel.CautareSedinteAsync(request);
        }
        
        public System.Threading.Tasks.Task<ExternalServiceCalls.ServiceReference2.CautareSedinteResponse> CautareSedinteAsync(System.DateTime dataSedinta, socisaV2.PortalWS.Institutie institutie) {
            ExternalServiceCalls.ServiceReference2.CautareSedinteRequest inValue = new ExternalServiceCalls.ServiceReference2.CautareSedinteRequest();
            inValue.Body = new ExternalServiceCalls.ServiceReference2.CautareSedinteRequestBody();
            inValue.Body.dataSedinta = dataSedinta;
            inValue.Body.institutie = institutie;
            return ((ExternalServiceCalls.ServiceReference2.QuerySoap)(this)).CautareSedinteAsync(inValue);
        }
    }
}
