//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace socisaV2.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DashboardResx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DashboardResx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("socisaV2.Resources.DashboardResx", typeof(DashboardResx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string ABOUT {
            get {
                return ResourceManager.GetString("ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign.
        /// </summary>
        public static string ASIGNEAZA {
            get {
                return ResourceManager.GetString("ASIGNEAZA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string CONTACT {
            get {
                return ResourceManager.GetString("CONTACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from which new Files since last login.
        /// </summary>
        public static string DIN_CARE_DOSARE_NOI_DE_LA_ULTIMUL_LOGIN {
            get {
                return ResourceManager.GetString("DIN_CARE_DOSARE_NOI_DE_LA_ULTIMUL_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid Files.
        /// </summary>
        public static string DOSARE_ACHITATE {
            get {
                return ResourceManager.GetString("DOSARE_ACHITATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partially paid Files.
        /// </summary>
        public static string DOSARE_ACHITATE_PARTIAL {
            get {
                return ResourceManager.GetString("DOSARE_ACHITATE_PARTIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted Files.
        /// </summary>
        public static string DOSARE_AVIZATE {
            get {
                return ResourceManager.GetString("DOSARE_AVIZATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted Files not yet sent.
        /// </summary>
        public static string DOSARE_AVIZATE_NEEXPEDIATE {
            get {
                return ResourceManager.GetString("DOSARE_AVIZATE_NEEXPEDIATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total accepted Files.
        /// </summary>
        public static string DOSARE_AVIZATE_TOTAL {
            get {
                return ResourceManager.GetString("DOSARE_AVIZATE_TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New CASCO files from last login.
        /// </summary>
        public static string DOSARE_CASCO_FROM_LAST_LOGIN {
            get {
                return ResourceManager.GetString("DOSARE_CASCO_FROM_LAST_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unassigned CASCO files.
        /// </summary>
        public static string DOSARE_CASCO_NEASIGNATE {
            get {
                return ResourceManager.GetString("DOSARE_CASCO_NEASIGNATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untouched CASCO files.
        /// </summary>
        public static string DOSARE_CASCO_NEOPERATE {
            get {
                return ResourceManager.GetString("DOSARE_CASCO_NEOPERATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total no. of CASCO files in data base.
        /// </summary>
        public static string DOSARE_CASCO_TOTAL {
            get {
                return ResourceManager.GetString("DOSARE_CASCO_TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files without scanned documents.
        /// </summary>
        public static string DOSARE_FARA_DOCUMENTE {
            get {
                return ResourceManager.GetString("DOSARE_FARA_DOCUMENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files without law suit.
        /// </summary>
        public static string DOSARE_FARA_PROCES {
            get {
                return ResourceManager.GetString("DOSARE_FARA_PROCES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New files from last login.
        /// </summary>
        public static string DOSARE_FROM_LAST_LOGIN {
            get {
                return ResourceManager.GetString("DOSARE_FROM_LAST_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete Files.
        /// </summary>
        public static string DOSARE_INCOMPLETE {
            get {
                return ResourceManager.GetString("DOSARE_INCOMPLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpaid Files.
        /// </summary>
        public static string DOSARE_NEACHITATE {
            get {
                return ResourceManager.GetString("DOSARE_NEACHITATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unassigned files.
        /// </summary>
        public static string DOSARE_NEASIGNATE {
            get {
                return ResourceManager.GetString("DOSARE_NEASIGNATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unassigned CASCO files from last login.
        /// </summary>
        public static string DOSARE_NEASIGNATE_CASCO_FROM_LAST_LOGIN {
            get {
                return ResourceManager.GetString("DOSARE_NEASIGNATE_CASCO_FROM_LAST_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unassigned files from last login.
        /// </summary>
        public static string DOSARE_NEASIGNATE_FROM_LAST_LOGIN {
            get {
                return ResourceManager.GetString("DOSARE_NEASIGNATE_FROM_LAST_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unassigned RCA files from last login.
        /// </summary>
        public static string DOSARE_NEASIGNATE_RCA_FROM_LAST_LOGIN {
            get {
                return ResourceManager.GetString("DOSARE_NEASIGNATE_RCA_FROM_LAST_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files to be accepted.
        /// </summary>
        public static string DOSARE_NEAVIZATE {
            get {
                return ResourceManager.GetString("DOSARE_NEAVIZATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untouched files.
        /// </summary>
        public static string DOSARE_NEOPERATE {
            get {
                return ResourceManager.GetString("DOSARE_NEOPERATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unassigned new loss party (CASCO) Files.
        /// </summary>
        public static string DOSARE_NOI_CASCO_NEASIGNATE {
            get {
                return ResourceManager.GetString("DOSARE_NOI_CASCO_NEASIGNATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untouched new loss party (CASCO) Files.
        /// </summary>
        public static string DOSARE_NOI_CASCO_NEOPERATE {
            get {
                return ResourceManager.GetString("DOSARE_NOI_CASCO_NEOPERATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unassigned new Files.
        /// </summary>
        public static string DOSARE_NOI_NEASIGNATE {
            get {
                return ResourceManager.GetString("DOSARE_NOI_NEASIGNATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untouched new Files.
        /// </summary>
        public static string DOSARE_NOI_NEOPERATE {
            get {
                return ResourceManager.GetString("DOSARE_NOI_NEOPERATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unassigned new guilty party (RCA) Files.
        /// </summary>
        public static string DOSARE_NOI_RCA_NEASIGNATE {
            get {
                return ResourceManager.GetString("DOSARE_NOI_RCA_NEASIGNATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untouched new guilty party (RCA) Files.
        /// </summary>
        public static string DOSARE_NOI_RCA_NEOPERATE {
            get {
                return ResourceManager.GetString("DOSARE_NOI_RCA_NEOPERATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New RCA files from last login.
        /// </summary>
        public static string DOSARE_RCA_FROM_LAST_LOGIN {
            get {
                return ResourceManager.GetString("DOSARE_RCA_FROM_LAST_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unassigned RCA files.
        /// </summary>
        public static string DOSARE_RCA_NEASIGNATE {
            get {
                return ResourceManager.GetString("DOSARE_RCA_NEASIGNATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untouched RCA files.
        /// </summary>
        public static string DOSARE_RCA_NEOPERATE {
            get {
                return ResourceManager.GetString("DOSARE_RCA_NEOPERATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total no. of RCA files in data base.
        /// </summary>
        public static string DOSARE_RCA_TOTAL {
            get {
                return ResourceManager.GetString("DOSARE_RCA_TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Files.
        /// </summary>
        public static string DOSARE_SELECTATE {
            get {
                return ResourceManager.GetString("DOSARE_SELECTATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total no. of files in data base.
        /// </summary>
        public static string DOSARE_TOTAL {
            get {
                return ResourceManager.GetString("DOSARE_TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export filtered Files list in Excel.
        /// </summary>
        public static string EXPORT_EXCEL {
            get {
                return ResourceManager.GetString("EXPORT_EXCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show filtered Files.
        /// </summary>
        public static string FILTER_IN_INTERFACE {
            get {
                return ResourceManager.GetString("FILTER_IN_INTERFACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string MENU {
            get {
                return ResourceManager.GetString("MENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to files....
        /// </summary>
        public static string MERGI_LA_DOSARE {
            get {
                return ResourceManager.GetString("MERGI_LA_DOSARE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to messages....
        /// </summary>
        public static string MERGI_LA_MESAJE {
            get {
                return ResourceManager.GetString("MERGI_LA_MESAJE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to law suits....
        /// </summary>
        public static string MERGI_LA_PROCESE {
            get {
                return ResourceManager.GetString("MERGI_LA_PROCESE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New messages.
        /// </summary>
        public static string MESAJE_NOI {
            get {
                return ResourceManager.GetString("MESAJE_NOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New messages (NEW DOCUMENT).
        /// </summary>
        public static string MESAJE_NOI_DOCUMENT_NOU {
            get {
                return ResourceManager.GetString("MESAJE_NOI_DOCUMENT_NOU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New messages (NEW FILE).
        /// </summary>
        public static string MESAJE_NOI_DOSAR_NOU {
            get {
                return ResourceManager.GetString("MESAJE_NOI_DOSAR_NOU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New law suits.
        /// </summary>
        public static string PROCESE_NOI_TOTAL {
            get {
                return ResourceManager.GetString("PROCESE_NOI_TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total no. of law suits as Defendant.
        /// </summary>
        public static string PROCESE_PARAT_TOTAL {
            get {
                return ResourceManager.GetString("PROCESE_PARAT_TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total no. of law suits as Accuser.
        /// </summary>
        public static string PROCESE_RECLAMANT_TOTAL {
            get {
                return ResourceManager.GetString("PROCESE_RECLAMANT_TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total no. of law suits in data base.
        /// </summary>
        public static string PROCESE_TOTAL {
            get {
                return ResourceManager.GetString("PROCESE_TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired law swits deadlines.
        /// </summary>
        public static string TERMENE_DEPASITE {
            get {
                return ResourceManager.GetString("TERMENE_DEPASITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Law suits deadlines in the next 7 days.
        /// </summary>
        public static string TERMENE_IN_URMATOARELE_7_ZILE {
            get {
                return ResourceManager.GetString("TERMENE_IN_URMATOARELE_7_ZILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance cancellation system.
        /// </summary>
        public static string TITLE {
            get {
                return ResourceManager.GetString("TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to following users.
        /// </summary>
        public static string TO_USERS {
            get {
                return ResourceManager.GetString("TO_USERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All unassigned Files.
        /// </summary>
        public static string TOATE_DOSARELE_NEASIGNATE {
            get {
                return ResourceManager.GetString("TOATE_DOSARELE_NEASIGNATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All untouched Files.
        /// </summary>
        public static string TOATE_DOSARELE_NEOPERATE {
            get {
                return ResourceManager.GetString("TOATE_DOSARELE_NEOPERATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All users.
        /// </summary>
        public static string TOTI_UTILIZATORII {
            get {
                return ResourceManager.GetString("TOTI_UTILIZATORII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected users.
        /// </summary>
        public static string UTILIZATORI_SELECTATI {
            get {
                return ResourceManager.GetString("UTILIZATORI_SELECTATI", resourceCulture);
            }
        }
    }
}
