//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace socisaV2.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DocumenteResx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DocumenteResx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("socisaV2.Resources.DocumenteResx", typeof(DocumenteResx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attached to File stage.
        /// </summary>
        public static string ASOCIAT_STADIULUI {
            get {
                return ResourceManager.GetString("ASOCIAT_STADIULUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach new document to file.
        /// </summary>
        public static string ATASEAZA_TITLE {
            get {
                return ResourceManager.GetString("ATASEAZA_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept/Refuse all documents.
        /// </summary>
        public static string AVIZARE_ALL_TITLE {
            get {
                return ResourceManager.GetString("AVIZARE_ALL_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept/Refuse selected document.
        /// </summary>
        public static string AVIZARE_TITLE {
            get {
                return ResourceManager.GetString("AVIZARE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name.
        /// </summary>
        public static string DENUMIRE_FISIER {
            get {
                return ResourceManager.GetString("DENUMIRE_FISIER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string DETALII {
            get {
                return ResourceManager.GetString("DETALII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Edit details for the selected document.
        /// </summary>
        public static string DETALII_TITLE {
            get {
                return ResourceManager.GetString("DETALII_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document is included in the file and accepted.
        /// </summary>
        public static string DOCUMENT_AVIZAT {
            get {
                return ResourceManager.GetString("DOCUMENT_AVIZAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot modify the documents of an accepted file!.
        /// </summary>
        public static string DOCUMENT_BLOCAT {
            get {
                return ResourceManager.GetString("DOCUMENT_BLOCAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ... or Drag&amp;Drop image or PDF files here.
        /// </summary>
        public static string DRAG_AND_DROP {
            get {
                return ResourceManager.GetString("DRAG_AND_DROP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only .jpg, .jpeg, .png, .bmp and .pdf files with maximum size of 20Mb are allowed!.
        /// </summary>
        public static string FISIERE_PERMISE {
            get {
                return ResourceManager.GetString("FISIERE_PERMISE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load scanned document(s)....
        /// </summary>
        public static string INCARCA_FISIERE {
            get {
                return ResourceManager.GetString("INCARCA_FISIERE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change document(s) type.
        /// </summary>
        public static string MODIFICARE_TIP_TITLE {
            get {
                return ResourceManager.GetString("MODIFICARE_TIP_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag&amp;Drop functionality is not supported by your browser.
        /// </summary>
        public static string NO_DRAG_AND_DROP {
            get {
                return ResourceManager.GetString("NO_DRAG_AND_DROP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore document from data base.
        /// </summary>
        public static string REGENERARE_TITLE {
            get {
                return ResourceManager.GetString("REGENERARE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove selected document from file.
        /// </summary>
        public static string STERGE_TITLE {
            get {
                return ResourceManager.GetString("STERGE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document type.
        /// </summary>
        public static string TIP_DOCUMENT {
            get {
                return ResourceManager.GetString("TIP_DOCUMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open selected document in a new window.
        /// </summary>
        public static string VIZUALIZARE_TITLE {
            get {
                return ResourceManager.GetString("VIZUALIZARE_TITLE", resourceCulture);
            }
        }
    }
}
