//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace socisaV2.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DosareResx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DosareResx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("socisaV2.Resources.DosareResx", typeof(DosareResx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download documents.
        /// </summary>
        public static string _LABEL_DESCARCARE_DOCUMENTE {
            get {
                return ResourceManager.GetString("_LABEL_DESCARCARE_DOCUMENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download grouped documents.
        /// </summary>
        public static string _LABEL_DESCARCARE_DOCUMENTE_CERERE_GRUPATE {
            get {
                return ResourceManager.GetString("_LABEL_DESCARCARE_DOCUMENTE_CERERE_GRUPATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download request documents, grouped by document type.
        /// </summary>
        public static string _LABEL_DESCARCARE_DOCUMENTE_CERERE_GRUPATE_TITLE {
            get {
                return ResourceManager.GetString("_LABEL_DESCARCARE_DOCUMENTE_CERERE_GRUPATE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download ungrouped documents.
        /// </summary>
        public static string _LABEL_DESCARCARE_DOCUMENTE_CERERE_NEGRUPATE {
            get {
                return ResourceManager.GetString("_LABEL_DESCARCARE_DOCUMENTE_CERERE_NEGRUPATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download request documents, ungrouped.
        /// </summary>
        public static string _LABEL_DESCARCARE_DOCUMENTE_CERERE_NEGRUPATE_TITLE {
            get {
                return ResourceManager.GetString("_LABEL_DESCARCARE_DOCUMENTE_CERERE_NEGRUPATE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email request.
        /// </summary>
        public static string _LABEL_EMAIL_CERERE {
            get {
                return ResourceManager.GetString("_LABEL_EMAIL_CERERE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send email with simple request.
        /// </summary>
        public static string _LABEL_EMAIL_CERERE_TITLE {
            get {
                return ResourceManager.GetString("_LABEL_EMAIL_CERERE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string _LABEL_EXPORT_BORDEROU_IN_EXCEL {
            get {
                return ResourceManager.GetString("_LABEL_EXPORT_BORDEROU_IN_EXCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export files to Excel.
        /// </summary>
        public static string _LABEL_EXPORT_DOSARE_IN_EXCEL {
            get {
                return ResourceManager.GetString("_LABEL_EXPORT_DOSARE_IN_EXCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export files to Excel.
        /// </summary>
        public static string _LABEL_EXPORT_DOSARE_IN_EXCEL_TITLE {
            get {
                return ResourceManager.GetString("_LABEL_EXPORT_DOSARE_IN_EXCEL_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Files to Excel.
        /// </summary>
        public static string _LABEL_EXPORT_EXCEL {
            get {
                return ResourceManager.GetString("_LABEL_EXPORT_EXCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string _LABEL_TIPARIRE {
            get {
                return ResourceManager.GetString("_LABEL_TIPARIRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print complete request.
        /// </summary>
        public static string _LABEL_TIPARIRE_CERERE_COMPLETA {
            get {
                return ResourceManager.GetString("_LABEL_TIPARIRE_CERERE_COMPLETA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print complete request, including associated documents.
        /// </summary>
        public static string _LABEL_TIPARIRE_CERERE_COMPLETA_TITLE {
            get {
                return ResourceManager.GetString("_LABEL_TIPARIRE_CERERE_COMPLETA_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print request without documents.
        /// </summary>
        public static string _LABEL_TIPARIRE_CERERE_FARA_DOCUMENTE {
            get {
                return ResourceManager.GetString("_LABEL_TIPARIRE_CERERE_FARA_DOCUMENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print simple request, without associated documents.
        /// </summary>
        public static string _LABEL_TIPARIRE_CERERE_FARA_DOCUMENTE_TITLE {
            get {
                return ResourceManager.GetString("_LABEL_TIPARIRE_CERERE_FARA_DOCUMENTE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print request documents.
        /// </summary>
        public static string _LABEL_TIPARIRE_DOCUMENTE_CERERE {
            get {
                return ResourceManager.GetString("_LABEL_TIPARIRE_DOCUMENTE_CERERE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print only the documnets associated to the request.
        /// </summary>
        public static string _LABEL_TIPARIRE_DOCUMENTE_CERERE_TITLE {
            get {
                return ResourceManager.GetString("_LABEL_TIPARIRE_DOCUMENTE_CERERE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAID.
        /// </summary>
        public static string ACHITAT {
            get {
                return ResourceManager.GetString("ACHITAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PARTIALLY PAID.
        /// </summary>
        public static string ACHITAT_PARTIAL {
            get {
                return ResourceManager.GetString("ACHITAT_PARTIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXPIRED.
        /// </summary>
        public static string ACTIUNE_BADGE {
            get {
                return ResourceManager.GetString("ACTIUNE_BADGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CASCO Acceptance.
        /// </summary>
        public static string AVIZARE {
            get {
                return ResourceManager.GetString("AVIZARE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACCEPTED.
        /// </summary>
        public static string AVIZAT {
            get {
                return ResourceManager.GetString("AVIZAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACCEPTED.
        /// </summary>
        public static string AVIZAT_BADGE {
            get {
                return ResourceManager.GetString("AVIZAT_BADGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel active filters.
        /// </summary>
        public static string CANCEL_ACTIVE_FILTERS_TITLE {
            get {
                return ResourceManager.GetString("CANCEL_ACTIVE_FILTERS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amiable Assesment No..
        /// </summary>
        public static string CAZ {
            get {
                return ResourceManager.GetString("CAZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMPENSATED.
        /// </summary>
        public static string COMPENSAT {
            get {
                return ResourceManager.GetString("COMPENSAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMPENSATED.
        /// </summary>
        public static string COMPENSAT_BADGE {
            get {
                return ResourceManager.GetString("COMPENSAT_BADGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PARTIALY COMPENSATED.
        /// </summary>
        public static string COMPENSAT_PARTIAL {
            get {
                return ResourceManager.GetString("COMPENSAT_PARTIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PARTIALY COMPENSATED.
        /// </summary>
        public static string COMPENSAT_PARTIAL_BADGE {
            get {
                return ResourceManager.GetString("COMPENSAT_PARTIAL_BADGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceptance Date.
        /// </summary>
        public static string DATA_AVIZARE {
            get {
                return ResourceManager.GetString("DATA_AVIZARE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to:.
        /// </summary>
        public static string DATA_AVIZARE_END {
            get {
                return ResourceManager.GetString("DATA_AVIZARE_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceptance Date.
        /// </summary>
        public static string DATA_AVIZARE_START {
            get {
                return ResourceManager.GetString("DATA_AVIZARE_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Date.
        /// </summary>
        public static string DATA_CREARE {
            get {
                return ResourceManager.GetString("DATA_CREARE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to:.
        /// </summary>
        public static string DATA_CREARE_END {
            get {
                return ResourceManager.GetString("DATA_CREARE_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Date.
        /// </summary>
        public static string DATA_CREARE_START {
            get {
                return ResourceManager.GetString("DATA_CREARE_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from:.
        /// </summary>
        public static string DATA_DE_LA {
            get {
                return ResourceManager.GetString("DATA_DE_LA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Date.
        /// </summary>
        public static string DATA_EVENIMENT {
            get {
                return ResourceManager.GetString("DATA_EVENIMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to:.
        /// </summary>
        public static string DATA_EVENIMENT_END {
            get {
                return ResourceManager.GetString("DATA_EVENIMENT_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Date.
        /// </summary>
        public static string DATA_EVENIMENT_START {
            get {
                return ResourceManager.GetString("DATA_EVENIMENT_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CASCO exit date.
        /// </summary>
        public static string DATA_IESIRE_CASCO {
            get {
                return ResourceManager.GetString("DATA_IESIRE_CASCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to:.
        /// </summary>
        public static string DATA_IESIRE_CASCO_END {
            get {
                return ResourceManager.GetString("DATA_IESIRE_CASCO_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CASCO exit date.
        /// </summary>
        public static string DATA_IESIRE_CASCO_START {
            get {
                return ResourceManager.GetString("DATA_IESIRE_CASCO_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RCA in date.
        /// </summary>
        public static string DATA_INTRARE_RCA {
            get {
                return ResourceManager.GetString("DATA_INTRARE_RCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to:.
        /// </summary>
        public static string DATA_INTRARE_RCA_END {
            get {
                return ResourceManager.GetString("DATA_INTRARE_RCA_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RCA in date.
        /// </summary>
        public static string DATA_INTRARE_RCA_START {
            get {
                return ResourceManager.GetString("DATA_INTRARE_RCA_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Date.
        /// </summary>
        public static string DATA_NOTIFICARE {
            get {
                return ResourceManager.GetString("DATA_NOTIFICARE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to:.
        /// </summary>
        public static string DATA_NOTIFICARE_END {
            get {
                return ResourceManager.GetString("DATA_NOTIFICARE_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Date.
        /// </summary>
        public static string DATA_NOTIFICARE_START {
            get {
                return ResourceManager.GetString("DATA_NOTIFICARE_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCA date.
        /// </summary>
        public static string DATA_SCA {
            get {
                return ResourceManager.GetString("DATA_SCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to:.
        /// </summary>
        public static string DATA_SCA_END {
            get {
                return ResourceManager.GetString("DATA_SCA_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCA Date.
        /// </summary>
        public static string DATA_SCA_START {
            get {
                return ResourceManager.GetString("DATA_SCA_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last modification date.
        /// </summary>
        public static string DATA_ULTIMEI_MODIFICARI {
            get {
                return ResourceManager.GetString("DATA_ULTIMEI_MODIFICARI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to:.
        /// </summary>
        public static string DATA_ULTIMEI_MODIFICARI_END {
            get {
                return ResourceManager.GetString("DATA_ULTIMEI_MODIFICARI_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last modification date.
        /// </summary>
        public static string DATA_ULTIMEI_MODIFICARI_START {
            get {
                return ResourceManager.GetString("DATA_ULTIMEI_MODIFICARI_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FILE DETAILS.
        /// </summary>
        public static string DETALII_DOSAR {
            get {
                return ResourceManager.GetString("DETALII_DOSAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details about the loss file.
        /// </summary>
        public static string DETALII_DOSAR_DAUNA_TITLE {
            get {
                return ResourceManager.GetString("DETALII_DOSAR_DAUNA_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOCUMENTS.
        /// </summary>
        public static string DOCUMENTE {
            get {
                return ResourceManager.GetString("DOCUMENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanned documents attached to the loss file.
        /// </summary>
        public static string DOCUMENTE_DOSAR_DAUNA_TITLE {
            get {
                return ResourceManager.GetString("DOCUMENTE_DOSAR_DAUNA_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File without scanned documents.
        /// </summary>
        public static string DOSAR_FARA_DOCUMENTE {
            get {
                return ResourceManager.GetString("DOSAR_FARA_DOCUMENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File without law suit.
        /// </summary>
        public static string DOSAR_FARA_PROCES {
            get {
                return ResourceManager.GetString("DOSAR_FARA_PROCES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |&lt;.
        /// </summary>
        public static string FIRST_DOSAR {
            get {
                return ResourceManager.GetString("FIRST_DOSAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate to first file.
        /// </summary>
        public static string FIRST_DOSAR_TITLE {
            get {
                return ResourceManager.GetString("FIRST_DOSAR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loss insured party (CASCO).
        /// </summary>
        public static string ID_ASIGURAT_CASCO {
            get {
                return ResourceManager.GetString("ID_ASIGURAT_CASCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guilty insured party (RCA).
        /// </summary>
        public static string ID_ASIGURAT_RCA {
            get {
                return ResourceManager.GetString("ID_ASIGURAT_RCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loss insured car plate no. (CASCO).
        /// </summary>
        public static string ID_AUTO_CASCO {
            get {
                return ResourceManager.GetString("ID_AUTO_CASCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guilty party car plate no. (RCA).
        /// </summary>
        public static string ID_AUTO_RCA {
            get {
                return ResourceManager.GetString("ID_AUTO_RCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guilty driver name (Intervener).
        /// </summary>
        public static string ID_INTERVENIENT {
            get {
                return ResourceManager.GetString("ID_INTERVENIENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loss insurer company (CASCO).
        /// </summary>
        public static string ID_SOCIETATE_CASCO {
            get {
                return ResourceManager.GetString("ID_SOCIETATE_CASCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guilty insurer company (RCA).
        /// </summary>
        public static string ID_SOCIETATE_RCA {
            get {
                return ResourceManager.GetString("ID_SOCIETATE_RCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Type.
        /// </summary>
        public static string ID_TIP_DOSAR {
            get {
                return ResourceManager.GetString("ID_TIP_DOSAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INCOMPLETE.
        /// </summary>
        public static string INCOMPLET {
            get {
                return ResourceManager.GetString("INCOMPLET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INCOMPLETE.
        /// </summary>
        public static string INCOMPLET_BADGE {
            get {
                return ResourceManager.GetString("INCOMPLET_BADGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File with law suit.
        /// </summary>
        public static string INSTANTA {
            get {
                return ResourceManager.GetString("INSTANTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;|.
        /// </summary>
        public static string LAST_DOSAR {
            get {
                return ResourceManager.GetString("LAST_DOSAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate to last file.
        /// </summary>
        public static string LAST_DOSAR_TITLE {
            get {
                return ResourceManager.GetString("LAST_DOSAR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loss files list.
        /// </summary>
        public static string LISTA_DOSARE {
            get {
                return ResourceManager.GetString("LISTA_DOSARE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show found files list.
        /// </summary>
        public static string LISTA_DOSARE_TITLE {
            get {
                return ResourceManager.GetString("LISTA_DOSARE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loss place.
        /// </summary>
        public static string LOC_ACCIDENT {
            get {
                return ResourceManager.GetString("LOC_ACCIDENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MESSAGES.
        /// </summary>
        public static string MESAJE {
            get {
                return ResourceManager.GetString("MESAJE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages related to the loss file.
        /// </summary>
        public static string MESAJE_DOSAR_DAUNA_TITLE {
            get {
                return ResourceManager.GetString("MESAJE_DOSAR_DAUNA_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOT PAID.
        /// </summary>
        public static string NEACHITAT {
            get {
                return ResourceManager.GetString("NEACHITAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TO BE ACCEPTED.
        /// </summary>
        public static string NEAVIZAT {
            get {
                return ResourceManager.GetString("NEAVIZAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TO BE ACCEPTED.
        /// </summary>
        public static string NEAVIZAT_BADGE {
            get {
                return ResourceManager.GetString("NEAVIZAT_BADGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOT COMPENSATED.
        /// </summary>
        public static string NECOMPENSAT {
            get {
                return ResourceManager.GetString("NECOMPENSAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOT COMPENSATED.
        /// </summary>
        public static string NECOMPENSAT_BADGE {
            get {
                return ResourceManager.GetString("NECOMPENSAT_BADGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;.
        /// </summary>
        public static string NEXT_DOSAR {
            get {
                return ResourceManager.GetString("NEXT_DOSAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate to next file.
        /// </summary>
        public static string NEXT_DOSAR_TITLE {
            get {
                return ResourceManager.GetString("NEXT_DOSAR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CASCO file no..
        /// </summary>
        public static string NR_DOSAR_CASCO {
            get {
                return ResourceManager.GetString("NR_DOSAR_CASCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CASCO exit no..
        /// </summary>
        public static string NR_IESIRE_CASCO {
            get {
                return ResourceManager.GetString("NR_IESIRE_CASCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RCA in no..
        /// </summary>
        public static string NR_INTRARE_RCA {
            get {
                return ResourceManager.GetString("NR_INTRARE_RCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loss party policy no. (CASCO).
        /// </summary>
        public static string NR_POLITA_CASCO {
            get {
                return ResourceManager.GetString("NR_POLITA_CASCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guilty party policy no. (RCA).
        /// </summary>
        public static string NR_POLITA_RCA {
            get {
                return ResourceManager.GetString("NR_POLITA_RCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCA no..
        /// </summary>
        public static string NR_SCA {
            get {
                return ResourceManager.GetString("NR_SCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no filtered files.
        /// </summary>
        public static string NU_SUNT_DOSARE_FILTRATE {
            get {
                return ResourceManager.GetString("NU_SUNT_DOSARE_FILTRATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observations.
        /// </summary>
        public static string OBSERVATII {
            get {
                return ResourceManager.GetString("OBSERVATII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string OPTIUNI {
            get {
                return ResourceManager.GetString("OPTIUNI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loss party (CASCO).
        /// </summary>
        public static string PAGUBIT_CASCO {
            get {
                return ResourceManager.GetString("PAGUBIT_CASCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAYMENTS.
        /// </summary>
        public static string PLATI {
            get {
                return ResourceManager.GetString("PLATI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payments attached to the loss file.
        /// </summary>
        public static string PLATI_DOSAR_DAUNA_TITLE {
            get {
                return ResourceManager.GetString("PLATI_DOSAR_DAUNA_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;.
        /// </summary>
        public static string PREV_DOSAR {
            get {
                return ResourceManager.GetString("PREV_DOSAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate to previous file.
        /// </summary>
        public static string PREV_DOSAR_TITLE {
            get {
                return ResourceManager.GetString("PREV_DOSAR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACTIONS.
        /// </summary>
        public static string PROCESE {
            get {
                return ResourceManager.GetString("PROCESE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Law suits attached to the loss file.
        /// </summary>
        public static string PROCESE_DOSAR_DAUNA_TITLE {
            get {
                return ResourceManager.GetString("PROCESE_DOSAR_DAUNA_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request has been sent before! Are you sure you want to send it again?!.
        /// </summary>
        public static string RESEND_EMAIL_CONFIRMATION_MESSAGE {
            get {
                return ResourceManager.GetString("RESEND_EMAIL_CONFIRMATION_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining amount to be paid.
        /// </summary>
        public static string REST_PLATA {
            get {
                return ResourceManager.GetString("REST_PLATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loss Reserve.
        /// </summary>
        public static string REZERVA_DAUNA {
            get {
                return ResourceManager.GetString("REZERVA_DAUNA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search/Filter.
        /// </summary>
        public static string SEARCH_TITLE {
            get {
                return ResourceManager.GetString("SEARCH_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send status.
        /// </summary>
        public static string SEND_STATUS {
            get {
                return ResourceManager.GetString("SEND_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to navigation.
        /// </summary>
        public static string SHOW_TITLE {
            get {
                return ResourceManager.GetString("SHOW_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stages.
        /// </summary>
        public static string STADII {
            get {
                return ResourceManager.GetString("STADII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loss file stages.
        /// </summary>
        public static string STADII_DOSAR_DAUNA_TITLE {
            get {
                return ResourceManager.GetString("STADII_DOSAR_DAUNA_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string STATUS {
            get {
                return ResourceManager.GetString("STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBNR Value.
        /// </summary>
        public static string SUMA_IBNR {
            get {
                return ResourceManager.GetString("SUMA_IBNR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string TITLE {
            get {
                return ResourceManager.GetString("TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USERS.
        /// </summary>
        public static string UTILIZATORI {
            get {
                return ResourceManager.GetString("UTILIZATORI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users assigned to the loss file.
        /// </summary>
        public static string UTILIZATORI_DOSAR_DAUNA_TITLE {
            get {
                return ResourceManager.GetString("UTILIZATORI_DOSAR_DAUNA_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign current file to users.
        /// </summary>
        public static string UTILIZATORI_TITLE {
            get {
                return ResourceManager.GetString("UTILIZATORI_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loss Value.
        /// </summary>
        public static string VALOARE_DAUNA {
            get {
                return ResourceManager.GetString("VALOARE_DAUNA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regress Value.
        /// </summary>
        public static string VALOARE_REGRES {
            get {
                return ResourceManager.GetString("VALOARE_REGRES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guilty party (RCA).
        /// </summary>
        public static string VINOVAT_RCA {
            get {
                return ResourceManager.GetString("VINOVAT_RCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VMD.
        /// </summary>
        public static string VMD {
            get {
                return ResourceManager.GetString("VMD", resourceCulture);
            }
        }
    }
}
