//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace socisaV2.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessagesResx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessagesResx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("socisaV2.Resources.ErrorMessagesResx", typeof(ErrorMessagesResx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The action already exists in the data base!.
        /// </summary>
        public static string actiuneExistenta {
            get {
                return ResourceManager.GetString("actiuneExistenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field already exists in the table!.
        /// </summary>
        public static string campInexistentInTabela {
            get {
                return ResourceManager.GetString("campInexistentInTabela", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string could not be converted into table field names!.
        /// </summary>
        public static string cannotConvertStringToTableColumns {
            get {
                return ResourceManager.GetString("cannotConvertStringToTableColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving the loss insured party (CASCO)!.
        /// </summary>
        public static string couldNotInsertAsiguratCasco {
            get {
                return ResourceManager.GetString("couldNotInsertAsiguratCasco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving the loss party company (CASCO)!.
        /// </summary>
        public static string couldNotInsertAsiguratorCasco {
            get {
                return ResourceManager.GetString("couldNotInsertAsiguratorCasco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving the guilty party company (RCA)!.
        /// </summary>
        public static string couldNotInsertAsiguratorRca {
            get {
                return ResourceManager.GetString("couldNotInsertAsiguratorRca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving the guilty insured party (RCA)!.
        /// </summary>
        public static string couldNotInsertAsiguratRca {
            get {
                return ResourceManager.GetString("couldNotInsertAsiguratRca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error savin the loss party car plate no.!.
        /// </summary>
        public static string couldNotInsertAutoCasco {
            get {
                return ResourceManager.GetString("couldNotInsertAutoCasco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving the guilty party car plate no.!.
        /// </summary>
        public static string couldNotInsertAutoRca {
            get {
                return ResourceManager.GetString("couldNotInsertAutoRca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving the Intervener (guilty driver)!.
        /// </summary>
        public static string couldNotInsertIntervenient {
            get {
                return ResourceManager.GetString("couldNotInsertIntervenient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file already exists in the data base!.
        /// </summary>
        public static string dosarExistent {
            get {
                return ResourceManager.GetString("dosarExistent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file doesn&apos;t have any attached document.
        /// </summary>
        public static string dosarFaraDocumente {
            get {
                return ResourceManager.GetString("dosarFaraDocumente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The File is missing!.
        /// </summary>
        public static string dosarInexistent {
            get {
                return ResourceManager.GetString("dosarInexistent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The File is not yet accepted!.
        /// </summary>
        public static string dosarNeavizat {
            get {
                return ResourceManager.GetString("dosarNeavizat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The wright already exists in the data base!.
        /// </summary>
        public static string dreptExistent {
            get {
                return ResourceManager.GetString("dreptExistent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in the &quot;Verification code&quot;!.
        /// </summary>
        public static string EMPTY_CODE {
            get {
                return ResourceManager.GetString("EMPTY_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in the Password!.
        /// </summary>
        public static string EMPTY_PASSWORD {
            get {
                return ResourceManager.GetString("EMPTY_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in the Username!.
        /// </summary>
        public static string EMPTY_USERNAME {
            get {
                return ResourceManager.GetString("EMPTY_USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;Action&quot; is mandatory!.
        /// </summary>
        public static string emptyAction {
            get {
                return ResourceManager.GetString("emptyAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;Loss party (CASCO)&quot; is mandatory!.
        /// </summary>
        public static string emptyAsiguratCasco {
            get {
                return ResourceManager.GetString("emptyAsiguratCasco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;Loss party company (CASCO)&quot; is mandatory!.
        /// </summary>
        public static string emptyAsiguratorCasco {
            get {
                return ResourceManager.GetString("emptyAsiguratorCasco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;Guilty party company (RCA)&quot; is mandatory!.
        /// </summary>
        public static string emptyAsiguratorRca {
            get {
                return ResourceManager.GetString("emptyAsiguratorRca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;Guilty party (RCA)&quot; is mandatory!.
        /// </summary>
        public static string emptyAsiguratRca {
            get {
                return ResourceManager.GetString("emptyAsiguratRca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;Loss party (CASCO) car plate no.&quot; is mandatory!.
        /// </summary>
        public static string emptyAutoCasco {
            get {
                return ResourceManager.GetString("emptyAutoCasco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;Guilty party (RCA) car plate no.&quot; is mandatory!.
        /// </summary>
        public static string emptyAutoRca {
            get {
                return ResourceManager.GetString("emptyAutoRca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;Body&quot; is not filled!.
        /// </summary>
        public static string emptyBody {
            get {
                return ResourceManager.GetString("emptyBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;Insurance company CIF no.&quot; is mandatory!.
        /// </summary>
        public static string emptyCuiSocietate {
            get {
                return ResourceManager.GetString("emptyCuiSocietate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Date is mandatory!.
        /// </summary>
        public static string emptyDataCompensari {
            get {
                return ResourceManager.GetString("emptyDataCompensari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;Contract date&quot; is mandatory!.
        /// </summary>
        public static string emptyDataContract {
            get {
                return ResourceManager.GetString("emptyDataContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;Submission date&quot; is mandatory!.
        /// </summary>
        public static string emptyDataDepunereProcese {
            get {
                return ResourceManager.GetString("emptyDataDepunereProcese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;Payment documment date&quot; is mandatory!.
        /// </summary>
        public static string emptyDataDocumentPlata {
            get {
                return ResourceManager.GetString("emptyDataDocumentPlata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;Event Date&quot; is mandatory!.
        /// </summary>
        public static string emptyDataEveniment {
            get {
                return ResourceManager.GetString("emptyDataEveniment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;Message date&quot; is mandatory!.
        /// </summary>
        public static string emptyDataMesaj {
            get {
                return ResourceManager.GetString("emptyDataMesaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;Date&quot; is mandatory!.
        /// </summary>
        public static string emptyDataProceseStadii {
            get {
                return ResourceManager.GetString("emptyDataProceseStadii", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;Sentence date&quot; is mandatory!.
        /// </summary>
        public static string emptyDataSentinta {
            get {
                return ResourceManager.GetString("emptyDataSentinta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;Insured party name&quot; is mandatory!.
        /// </summary>
        public static string emptyDenumireAsigurat {
            get {
                return ResourceManager.GetString("emptyDenumireAsigurat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;Wright name&quot; is mandatory!.
        /// </summary>
        public static string emptyDenumireDrept {
            get {
                return ResourceManager.GetString("emptyDenumireDrept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;File name&quot; is mandatory!.
        /// </summary>
        public static string emptyDenumireFisier {
            get {
                return ResourceManager.GetString("emptyDenumireFisier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;Intervener (guilty driver) name&quot; is mandatory!.
        /// </summary>
        public static string emptyDenumireIntervenient {
            get {
                return ResourceManager.GetString("emptyDenumireIntervenient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;Name&quot; is mandatory!.
        /// </summary>
        public static string emptyDenumireNomenclator {
            get {
                return ResourceManager.GetString("emptyDenumireNomenclator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;Part name&quot; is mandatory!.
        /// </summary>
        public static string emptyDenumireParte {
            get {
                return ResourceManager.GetString("emptyDenumireParte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;Insurance company short name&quot; is mandatory!.
        /// </summary>
        public static string emptyDenumireScurtaSocietate {
            get {
                return ResourceManager.GetString("emptyDenumireScurtaSocietate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;Insurance company name&quot; is mandatory!.
        /// </summary>
        public static string emptyDenumireSocietate {
            get {
                return ResourceManager.GetString("emptyDenumireSocietate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;Solution name&quot; is mandatory!.
        /// </summary>
        public static string emptyDenumireSolutie {
            get {
                return ResourceManager.GetString("emptyDenumireSolutie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;Status name&quot; is mandatory!.
        /// </summary>
        public static string emptyDenumireStadiu {
            get {
                return ResourceManager.GetString("emptyDenumireStadiu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The File is mandatory!.
        /// </summary>
        public static string emptyDosarCompensari {
            get {
                return ResourceManager.GetString("emptyDosarCompensari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;From&quot; is mandatory!.
        /// </summary>
        public static string emptyFrom {
            get {
                return ResourceManager.GetString("emptyFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The File associated with the message is mandatory!.
        /// </summary>
        public static string emptyIdDosar {
            get {
                return ResourceManager.GetString("emptyIdDosar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The File is mandatory!.
        /// </summary>
        public static string emptyIdDosarPlata {
            get {
                return ResourceManager.GetString("emptyIdDosarPlata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The payment type is mandatory!.
        /// </summary>
        public static string emptyIdTipPlata {
            get {
                return ResourceManager.GetString("emptyIdTipPlata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;Message body&quot; is mandatory!.
        /// </summary>
        public static string emptyMessageBody {
            get {
                return ResourceManager.GetString("emptyMessageBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;Message receiver&quot; is mandatory!.
        /// </summary>
        public static string emptyMessageReceiver {
            get {
                return ResourceManager.GetString("emptyMessageReceiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;Message sender&quot; is mandatory!.
        /// </summary>
        public static string emptyMessageSender {
            get {
                return ResourceManager.GetString("emptyMessageSender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;Message subject&quot; is mandatory!.
        /// </summary>
        public static string emptyMessageSubject {
            get {
                return ResourceManager.GetString("emptyMessageSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message ID is missing!.
        /// </summary>
        public static string emptyNotificareId {
            get {
                return ResourceManager.GetString("emptyNotificareId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message text body is mandatory!.
        /// </summary>
        public static string emptyNotificareText {
            get {
                return ResourceManager.GetString("emptyNotificareText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;Car plate no.&quot; is mandatory!.
        /// </summary>
        public static string emptyNrAuto {
            get {
                return ResourceManager.GetString("emptyNrAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;Contract no.&quot; is mandatory!.
        /// </summary>
        public static string emptyNrContract {
            get {
                return ResourceManager.GetString("emptyNrContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;Payment documment no.&quot; is mandatory!.
        /// </summary>
        public static string emptyNrDocumentPlata {
            get {
                return ResourceManager.GetString("emptyNrDocumentPlata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;CASCO file no.&quot; is mandatory!.
        /// </summary>
        public static string emptyNrDosarCasco {
            get {
                return ResourceManager.GetString("emptyNrDosarCasco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;Action Court number&quot; is mandatory!.
        /// </summary>
        public static string emptyNrDosarInstantaProcese {
            get {
                return ResourceManager.GetString("emptyNrDosarInstantaProcese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;Action internal number&quot; is mandatory!.
        /// </summary>
        public static string emptyNrInternProcese {
            get {
                return ResourceManager.GetString("emptyNrInternProcese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;CASCO policy no.&quot; is mandatory!.
        /// </summary>
        public static string emptyNrPolitaCasco {
            get {
                return ResourceManager.GetString("emptyNrPolitaCasco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;RCA policy no.&quot; is mandatory!.
        /// </summary>
        public static string emptyNrPolitaRca {
            get {
                return ResourceManager.GetString("emptyNrPolitaRca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;Sentence no.&quot; is mandatory!.
        /// </summary>
        public static string emptyNrSentinta {
            get {
                return ResourceManager.GetString("emptyNrSentinta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;Action name&quot; is mandatory!.
        /// </summary>
        public static string emptyNumeAction {
            get {
                return ResourceManager.GetString("emptyNumeAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;Setting name&quot; is mandatory!.
        /// </summary>
        public static string emptyNumeSetare {
            get {
                return ResourceManager.GetString("emptyNumeSetare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;Operation&quot; is mandatory!.
        /// </summary>
        public static string emptyOperation {
            get {
                return ResourceManager.GetString("emptyOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;Penalties&quot; is mandatory!.
        /// </summary>
        public static string emptyPenalitatiProcese {
            get {
                return ResourceManager.GetString("emptyPenalitatiProcese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;Loss party (CASCO) policy no.&quot; is mandatory!.
        /// </summary>
        public static string emptyPolitaCasco {
            get {
                return ResourceManager.GetString("emptyPolitaCasco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;Guilty party (RCA) policy no.&quot; is mandatory.
        /// </summary>
        public static string emptyPolitaRca {
            get {
                return ResourceManager.GetString("emptyPolitaRca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;Court file&quot; is mandatory!.
        /// </summary>
        public static string emptyProcesProceseStadii {
            get {
                return ResourceManager.GetString("emptyProcesProceseStadii", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Rest is mandatory!.
        /// </summary>
        public static string emptyRestCompensari {
            get {
                return ResourceManager.GetString("emptyRestCompensari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;Car chassis identification no.&quot; is mandatory!.
        /// </summary>
        public static string emptySerieSasiuAuto {
            get {
                return ResourceManager.GetString("emptySerieSasiuAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;Solution&quot; is mandatory!.
        /// </summary>
        public static string emptySolutieSentinta {
            get {
                return ResourceManager.GetString("emptySolutieSentinta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;Stage&quot; is mandatory!.
        /// </summary>
        public static string emptyStadiuProceseStadii {
            get {
                return ResourceManager.GetString("emptyStadiuProceseStadii", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;Subject&quot; is mandatory!.
        /// </summary>
        public static string emptySubject {
            get {
                return ResourceManager.GetString("emptySubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Amount is mandatory!.
        /// </summary>
        public static string emptySumaCompensari {
            get {
                return ResourceManager.GetString("emptySumaCompensari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;Payment amount&quot; is mandatory!.
        /// </summary>
        public static string emptySumaPlata {
            get {
                return ResourceManager.GetString("emptySumaPlata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;Requested amount&quot; is mandatory!.
        /// </summary>
        public static string emptySumaSolicitataProcese {
            get {
                return ResourceManager.GetString("emptySumaSolicitataProcese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;Document type name&quot; is mandatory!.
        /// </summary>
        public static string emptyTipDocument {
            get {
                return ResourceManager.GetString("emptyTipDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;File type&quot; is mandatory!.
        /// </summary>
        public static string emptyTipDosar {
            get {
                return ResourceManager.GetString("emptyTipDosar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;To&quot; is mandatory!.
        /// </summary>
        public static string emptyTo {
            get {
                return ResourceManager.GetString("emptyTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;User name&quot; is mandatory!.
        /// </summary>
        public static string emptyUserName {
            get {
                return ResourceManager.GetString("emptyUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;User password&quot; is mandatory!.
        /// </summary>
        public static string emptyUserPassword {
            get {
                return ResourceManager.GetString("emptyUserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;User type&quot; field is mandatory!.
        /// </summary>
        public static string emptyUserType {
            get {
                return ResourceManager.GetString("emptyUserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;Loss value&quot; is mandatory!.
        /// </summary>
        public static string emptyValoareDauna {
            get {
                return ResourceManager.GetString("emptyValoareDauna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;Regress value&quot; is mandatory!.
        /// </summary>
        public static string emptyValoareRegres {
            get {
                return ResourceManager.GetString("emptyValoareRegres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;Setting value&quot; is mandatory!.
        /// </summary>
        public static string emptyValoareSetare {
            get {
                return ResourceManager.GetString("emptyValoareSetare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Athentication failled!.
        /// </summary>
        public static string FAILED_LOGIN {
            get {
                return ResourceManager.GetString("FAILED_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The intervener (guilty driver) already exists in the data base!.
        /// </summary>
        public static string intervenientExistent {
            get {
                return ResourceManager.GetString("intervenientExistent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected record has references in another table(s) and can not be deleted!.
        /// </summary>
        public static string mySlq_1451 {
            get {
                return ResourceManager.GetString("mySlq_1451", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already an {1} with the same name in the data base!.
        /// </summary>
        public static string mySql_1169 {
            get {
                return ResourceManager.GetString("mySql_1169", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The loss party company (CASCO) from the Excel file is not in the database. Are you sure you want to insert a new company in the database?.
        /// </summary>
        public static string newAsiguratorCasco {
            get {
                return ResourceManager.GetString("newAsiguratorCasco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The guilty party company (RCA) from the Excel file is not in the database. Are you sure you want to insert a new company in the database?.
        /// </summary>
        public static string newAsiguratorRca {
            get {
                return ResourceManager.GetString("newAsiguratorRca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already an Action with the same Court number in the data base!.
        /// </summary>
        public static string numarDosarInstantaProceseExistent {
            get {
                return ResourceManager.GetString("numarDosarInstantaProceseExistent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already an Action with the same Internal number in the data base!.
        /// </summary>
        public static string numarInternProceseExistent {
            get {
                return ResourceManager.GetString("numarInternProceseExistent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passwords don&apos;t match!.
        /// </summary>
        public static string passwordsDontMatch {
            get {
                return ResourceManager.GetString("passwordsDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The payment exists in the data base!.
        /// </summary>
        public static string plataExistenta {
            get {
                return ResourceManager.GetString("plataExistenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The company already exists in the data base!.
        /// </summary>
        public static string societateExistenta {
            get {
                return ResourceManager.GetString("societateExistenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorised user!.
        /// </summary>
        public static string unauthorisedUser {
            get {
                return ResourceManager.GetString("unauthorisedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file type!.
        /// </summary>
        public static string unsupportedFormat {
            get {
                return ResourceManager.GetString("unsupportedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The enterd verification code doesn&apos;t match the one send by email!.
        /// </summary>
        public static string VERIFICATION_CODE_DONT_MATCH {
            get {
                return ResourceManager.GetString("VERIFICATION_CODE_DONT_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The verification code has expired!.
        /// </summary>
        public static string VERIFICATION_CODE_EXPIRED {
            get {
                return ResourceManager.GetString("VERIFICATION_CODE_EXPIRED", resourceCulture);
            }
        }
    }
}
