//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace socisaV2.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MenuResx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MenuResx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("socisaV2.Resources.MenuResx", typeof(MenuResx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        public static string ADMINISTRARE {
            get {
                return ResourceManager.GetString("ADMINISTRARE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancellations.
        /// </summary>
        public static string COMPENSARI {
            get {
                return ResourceManager.GetString("COMPENSARI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string DASHBOARD {
            get {
                return ResourceManager.GetString("DASHBOARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string DOSARE {
            get {
                return ResourceManager.GetString("DOSARE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EDITARE {
            get {
                return ResourceManager.GetString("EDITARE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string IMPORT {
            get {
                return ResourceManager.GetString("IMPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File manager.
        /// </summary>
        public static string MANAGER_FISIERE {
            get {
                return ResourceManager.GetString("MANAGER_FISIERE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nomenclatures.
        /// </summary>
        public static string NOMENCLATOARE {
            get {
                return ResourceManager.GetString("NOMENCLATOARE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email notifications.
        /// </summary>
        public static string NOTIFICARI {
            get {
                return ResourceManager.GetString("NOTIFICARI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payments.
        /// </summary>
        public static string PLATI {
            get {
                return ResourceManager.GetString("PLATI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string RAPOARTE {
            get {
                return ResourceManager.GetString("RAPOARTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files reports.
        /// </summary>
        public static string RAPOARTE_DOSARE {
            get {
                return ResourceManager.GetString("RAPOARTE_DOSARE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance companies.
        /// </summary>
        public static string SOCIETATI_ASIGURARE {
            get {
                return ResourceManager.GetString("SOCIETATI_ASIGURARE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stages.
        /// </summary>
        public static string STADII {
            get {
                return ResourceManager.GetString("STADII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Law suits deadlines.
        /// </summary>
        public static string TERMENE_PORTAL {
            get {
                return ResourceManager.GetString("TERMENE_PORTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string UTILIZATORI {
            get {
                return ResourceManager.GetString("UTILIZATORI", resourceCulture);
            }
        }
    }
}
