//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace socisaV2.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MesajeResx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MesajeResx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("socisaV2.Resources.MesajeResx", typeof(MesajeResx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New message.
        /// </summary>
        public static string ADAUGA_TITLE {
            get {
                return ResourceManager.GetString("ADAUGA_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show messages.
        /// </summary>
        public static string AFISEAZA_TITLE {
            get {
                return ResourceManager.GetString("AFISEAZA_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message body.
        /// </summary>
        public static string BODY {
            get {
                return ResourceManager.GetString("BODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string DATA {
            get {
                return ResourceManager.GetString("DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from which new messages.
        /// </summary>
        public static string DIN_CARE {
            get {
                return ResourceManager.GetString("DIN_CARE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter messages.
        /// </summary>
        public static string FILTRARE_TITLE {
            get {
                return ResourceManager.GetString("FILTRARE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string ID_DOSAR {
            get {
                return ResourceManager.GetString("ID_DOSAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string ID_SENDER {
            get {
                return ResourceManager.GetString("ID_SENDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message type.
        /// </summary>
        public static string ID_TIP_MESAJ {
            get {
                return ResourceManager.GetString("ID_TIP_MESAJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importance.
        /// </summary>
        public static string IMPORTANTA {
            get {
                return ResourceManager.GetString("IMPORTANTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loss party (CASCO) messages.
        /// </summary>
        public static string MESAJE_CASCO {
            get {
                return ResourceManager.GetString("MESAJE_CASCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guilty party (RCA) messages.
        /// </summary>
        public static string MESAJE_RCA {
            get {
                return ResourceManager.GetString("MESAJE_RCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply to message.
        /// </summary>
        public static string RASPUNDE_TITLE {
            get {
                return ResourceManager.GetString("RASPUNDE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string REFRESH_TITLE {
            get {
                return ResourceManager.GetString("REFRESH_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply to.
        /// </summary>
        public static string REPLY_TO {
            get {
                return ResourceManager.GetString("REPLY_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string SUBIECT {
            get {
                return ResourceManager.GetString("SUBIECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All messages.
        /// </summary>
        public static string TOATE_MESAJELE {
            get {
                return ResourceManager.GetString("TOATE_MESAJELE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total messages.
        /// </summary>
        public static string TOTAL_MESAJE {
            get {
                return ResourceManager.GetString("TOTAL_MESAJE", resourceCulture);
            }
        }
    }
}
