//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace socisaV2.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NotificariEmailResx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NotificariEmailResx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("socisaV2.Resources.NotificariEmailResx", typeof(NotificariEmailResx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event type.
        /// </summary>
        public static string EVENT_TYPE {
            get {
                return ResourceManager.GetString("EVENT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel Export.
        /// </summary>
        public static string EXPORT_EXCEL {
            get {
                return ResourceManager.GetString("EXPORT_EXCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string FILTER {
            get {
                return ResourceManager.GetString("FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark as verified.
        /// </summary>
        public static string MARK_READ {
            get {
                return ResourceManager.GetString("MARK_READ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Id.
        /// </summary>
        public static string MESSAGE_ID {
            get {
                return ResourceManager.GetString("MESSAGE_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message text.
        /// </summary>
        public static string MESSAGE_TEXT {
            get {
                return ResourceManager.GetString("MESSAGE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CASCO File No..
        /// </summary>
        public static string NR_DOSAR_CASCO {
            get {
                return ResourceManager.GetString("NR_DOSAR_CASCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipients.
        /// </summary>
        public static string RECIPIENTS {
            get {
                return ResourceManager.GetString("RECIPIENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checked.
        /// </summary>
        public static string TIME_CHECKED {
            get {
                return ResourceManager.GetString("TIME_CHECKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp.
        /// </summary>
        public static string TIMESTAMP {
            get {
                return ResourceManager.GetString("TIMESTAMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp (to):.
        /// </summary>
        public static string TimeStampEnd {
            get {
                return ResourceManager.GetString("TimeStampEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp (from):.
        /// </summary>
        public static string TimeStampStart {
            get {
                return ResourceManager.GetString("TimeStampStart", resourceCulture);
            }
        }
    }
}
