//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace socisaV2.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProceseResx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProceseResx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("socisaV2.Resources.ProceseResx", typeof(ProceseResx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Action to email.
        /// </summary>
        public static string _LABEL_EMAIL_ACTIUNE {
            get {
                return ResourceManager.GetString("_LABEL_EMAIL_ACTIUNE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Action to email.
        /// </summary>
        public static string _LABEL_EMAIL_ACTIUNE_TITLE {
            get {
                return ResourceManager.GetString("_LABEL_EMAIL_ACTIUNE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Actions to Excel.
        /// </summary>
        public static string _LABEL_EXPORT_EXCEL {
            get {
                return ResourceManager.GetString("_LABEL_EXPORT_EXCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export filtered Actions to Excel.
        /// </summary>
        public static string _LABEL_EXPORT_PROCESE_IN_EXCEL {
            get {
                return ResourceManager.GetString("_LABEL_EXPORT_PROCESE_IN_EXCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export filtered Actions to Excel.
        /// </summary>
        public static string _LABEL_EXPORT_PROCESE_IN_EXCEL_TITLE {
            get {
                return ResourceManager.GetString("_LABEL_EXPORT_PROCESE_IN_EXCEL_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Court deadlines report.
        /// </summary>
        public static string _LABEL_RAPORT_TERMENE {
            get {
                return ResourceManager.GetString("_LABEL_RAPORT_TERMENE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Court deadlines report.
        /// </summary>
        public static string _LABEL_RAPORT_TERMENE_TITLE {
            get {
                return ResourceManager.GetString("_LABEL_RAPORT_TERMENE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string _LABEL_TIPARIRE {
            get {
                return ResourceManager.GetString("_LABEL_TIPARIRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Action.
        /// </summary>
        public static string _LABEL_TIPARIRE_ACTIUNE {
            get {
                return ResourceManager.GetString("_LABEL_TIPARIRE_ACTIUNE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Action.
        /// </summary>
        public static string _LABEL_TIPARIRE_ACTIUNE_TITLE {
            get {
                return ResourceManager.GetString("_LABEL_TIPARIRE_ACTIUNE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other judiciary expenses.
        /// </summary>
        public static string ALTE_CHELTUIELI_JUDECATA {
            get {
                return ResourceManager.GetString("ALTE_CHELTUIELI_JUDECATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string CALITATE {
            get {
                return ResourceManager.GetString("CALITATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third party type.
        /// </summary>
        public static string CALITATE_TERT {
            get {
                return ResourceManager.GetString("CALITATE_TERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel active filters.
        /// </summary>
        public static string CANCEL_ACTIVE_FILTERS_TITLE {
            get {
                return ResourceManager.GetString("CANCEL_ACTIVE_FILTERS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enforcement expenses.
        /// </summary>
        public static string CHELTUIELI_EXECUTARE {
            get {
                return ResourceManager.GetString("CHELTUIELI_EXECUTARE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Granted judiciary expenses.
        /// </summary>
        public static string CHELTUIELI_JUDECATA_ACORDATE {
            get {
                return ResourceManager.GetString("CHELTUIELI_JUDECATA_ACORDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small publicity expenses.
        /// </summary>
        public static string CHELTUIELI_MICA_PUBLICITATE {
            get {
                return ResourceManager.GetString("CHELTUIELI_MICA_PUBLICITATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to add new Action to the current selected Loss file?!.
        /// </summary>
        public static string CONFIRM_ADD_TO_CURRENT_FILE_MESSAGE {
            get {
                return ResourceManager.GetString("CONFIRM_ADD_TO_CURRENT_FILE_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from:.
        /// </summary>
        public static string DATA_DE_LA {
            get {
                return ResourceManager.GetString("DATA_DE_LA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission date.
        /// </summary>
        public static string DATA_DEPUNERE {
            get {
                return ResourceManager.GetString("DATA_DEPUNERE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to:.
        /// </summary>
        public static string DATA_DEPUNERE_END {
            get {
                return ResourceManager.GetString("DATA_DEPUNERE_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission date.
        /// </summary>
        public static string DATA_DEPUNERE_START {
            get {
                return ResourceManager.GetString("DATA_DEPUNERE_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enforcement date.
        /// </summary>
        public static string DATA_EXECUTARE {
            get {
                return ResourceManager.GetString("DATA_EXECUTARE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to:.
        /// </summary>
        public static string DATA_EXECUTARE_END {
            get {
                return ResourceManager.GetString("DATA_EXECUTARE_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enforcement date.
        /// </summary>
        public static string DATA_EXECUTARE_START {
            get {
                return ResourceManager.GetString("DATA_EXECUTARE_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to:.
        /// </summary>
        public static string DATA_PANA_LA {
            get {
                return ResourceManager.GetString("DATA_PANA_LA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCA Date.
        /// </summary>
        public static string DATA_SCA {
            get {
                return ResourceManager.GetString("DATA_SCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to:.
        /// </summary>
        public static string DATA_SCA_END {
            get {
                return ResourceManager.GetString("DATA_SCA_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCA Date.
        /// </summary>
        public static string DATA_SCA_START {
            get {
                return ResourceManager.GetString("DATA_SCA_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to:.
        /// </summary>
        public static string DATA_STADIU_END {
            get {
                return ResourceManager.GetString("DATA_STADIU_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage date.
        /// </summary>
        public static string DATA_STADIU_START {
            get {
                return ResourceManager.GetString("DATA_STADIU_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Granted compensation.
        /// </summary>
        public static string DESPAGUBIRE_ACORDATA {
            get {
                return ResourceManager.GetString("DESPAGUBIRE_ACORDATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate to the first Action.
        /// </summary>
        public static string FIRST_PROCES_TITLE {
            get {
                return ResourceManager.GetString("FIRST_PROCES_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Court bar.
        /// </summary>
        public static string ID_COMPLET {
            get {
                return ResourceManager.GetString("ID_COMPLET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract.
        /// </summary>
        public static string ID_CONTRACT {
            get {
                return ResourceManager.GetString("ID_CONTRACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Court.
        /// </summary>
        public static string ID_INSTANTA {
            get {
                return ResourceManager.GetString("ID_INSTANTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defendant.
        /// </summary>
        public static string ID_PARAT {
            get {
                return ResourceManager.GetString("ID_PARAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current stage.
        /// </summary>
        public static string ID_PROCES_STADIU {
            get {
                return ResourceManager.GetString("ID_PROCES_STADIU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accuser.
        /// </summary>
        public static string ID_RECLAMANT {
            get {
                return ResourceManager.GetString("ID_RECLAMANT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third party.
        /// </summary>
        public static string ID_TERT {
            get {
                return ResourceManager.GetString("ID_TERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action type.
        /// </summary>
        public static string ID_TIP_PROCES {
            get {
                return ResourceManager.GetString("ID_TIP_PROCES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents attached to Action.
        /// </summary>
        public static string INFO_DOCUMENTE_DOSAR {
            get {
                return ResourceManager.GetString("INFO_DOCUMENTE_DOSAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General information about the Action.
        /// </summary>
        public static string INFO_GENERALE_DOSAR {
            get {
                return ResourceManager.GetString("INFO_GENERALE_DOSAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Law suit informations from just.ro portal.
        /// </summary>
        public static string INFO_PORTAL {
            get {
                return ResourceManager.GetString("INFO_PORTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action stages.
        /// </summary>
        public static string INFO_STADII_DOSAR {
            get {
                return ResourceManager.GetString("INFO_STADII_DOSAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate to the last Action.
        /// </summary>
        public static string LAST_PROCES_TITLE {
            get {
                return ResourceManager.GetString("LAST_PROCES_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions list.
        /// </summary>
        public static string LISTA_PROCESE {
            get {
                return ResourceManager.GetString("LISTA_PROCESE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions list.
        /// </summary>
        public static string LISTA_PROCESE_TITLE {
            get {
                return ResourceManager.GetString("LISTA_PROCESE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring.
        /// </summary>
        public static string MONITORIZARE {
            get {
                return ResourceManager.GetString("MONITORIZARE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate to the next Action.
        /// </summary>
        public static string NEXT_PROCES_TITLE {
            get {
                return ResourceManager.GetString("NEXT_PROCES_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casco file no..
        /// </summary>
        public static string NR_DOSAR_CASCO {
            get {
                return ResourceManager.GetString("NR_DOSAR_CASCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enforcement file no..
        /// </summary>
        public static string NR_DOSAR_EXECUTARE {
            get {
                return ResourceManager.GetString("NR_DOSAR_EXECUTARE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Court no..
        /// </summary>
        public static string NR_DOSAR_INSTANTA {
            get {
                return ResourceManager.GetString("NR_DOSAR_INSTANTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action internal no..
        /// </summary>
        public static string NR_INTERN {
            get {
                return ResourceManager.GetString("NR_INTERN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCA no..
        /// </summary>
        public static string NR_SCA {
            get {
                return ResourceManager.GetString("NR_SCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no filtered Actions.
        /// </summary>
        public static string NU_SUNT_PROCESE_FILTRATE {
            get {
                return ResourceManager.GetString("NU_SUNT_PROCESE_FILTRATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string OBSERVATII {
            get {
                return ResourceManager.GetString("OBSERVATII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lawyer fee.
        /// </summary>
        public static string ONORARIU_AVOCAT {
            get {
                return ResourceManager.GetString("ONORARIU_AVOCAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enforcement lawyer fee.
        /// </summary>
        public static string ONORARIU_AVOCAT_EXECUTARE {
            get {
                return ResourceManager.GetString("ONORARIU_AVOCAT_EXECUTARE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiduciary fee.
        /// </summary>
        public static string ONORARIU_CURATOR {
            get {
                return ResourceManager.GetString("ONORARIU_CURATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expert fee.
        /// </summary>
        public static string ONORARIU_EXPERT {
            get {
                return ResourceManager.GetString("ONORARIU_EXPERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string OPTIUNI {
            get {
                return ResourceManager.GetString("OPTIUNI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Penalties.
        /// </summary>
        public static string PENALITATI {
            get {
                return ResourceManager.GetString("PENALITATI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate to the previous Action.
        /// </summary>
        public static string PREV_PROCES_TITLE {
            get {
                return ResourceManager.GetString("PREV_PROCES_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Action has been sent before! Are you sure you want to send it again?!.
        /// </summary>
        public static string RESEND_EMAIL_CONFIRMATION_MESSAGE {
            get {
                return ResourceManager.GetString("RESEND_EMAIL_CONFIRMATION_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search/Filter.
        /// </summary>
        public static string SEARCH_TITLE {
            get {
                return ResourceManager.GetString("SEARCH_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to navigation.
        /// </summary>
        public static string SHOW_TITLE {
            get {
                return ResourceManager.GetString("SHOW_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage.
        /// </summary>
        public static string STADIU {
            get {
                return ResourceManager.GetString("STADIU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested amount.
        /// </summary>
        public static string SUMA_SOLICITATA {
            get {
                return ResourceManager.GetString("SUMA_SOLICITATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stamp duty.
        /// </summary>
        public static string TAXA_TIMBRU {
            get {
                return ResourceManager.GetString("TAXA_TIMBRU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reexamination stamp duty.
        /// </summary>
        public static string TAXA_TIMBRU_REEXAMINARE {
            get {
                return ResourceManager.GetString("TAXA_TIMBRU_REEXAMINARE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Judiciary stamp duty.
        /// </summary>
        public static string TIMBRU_JUDICIAR {
            get {
                return ResourceManager.GetString("TIMBRU_JUDICIAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Penalty days.
        /// </summary>
        public static string ZILE_PENALIZARI {
            get {
                return ResourceManager.GetString("ZILE_PENALIZARI", resourceCulture);
            }
        }
    }
}
