//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace socisaV2.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProceseStadiiResx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProceseStadiiResx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("socisaV2.Resources.ProceseStadiiResx", typeof(ProceseStadiiResx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add scanned documents.
        /// </summary>
        public static string ADAUGA_DOCUMENTE_SCANATE {
            get {
                return ResourceManager.GetString("ADAUGA_DOCUMENTE_SCANATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string DATA {
            get {
                return ResourceManager.GetString("DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string ID_DOSAR {
            get {
                return ResourceManager.GetString("ID_DOSAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Court file.
        /// </summary>
        public static string ID_PROCES {
            get {
                return ResourceManager.GetString("ID_PROCES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sentence.
        /// </summary>
        public static string ID_SENTINTA {
            get {
                return ResourceManager.GetString("ID_SENTINTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage.
        /// </summary>
        public static string ID_STADIU {
            get {
                return ResourceManager.GetString("ID_STADIU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string OBSERVATII {
            get {
                return ResourceManager.GetString("OBSERVATII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour.
        /// </summary>
        public static string ORA {
            get {
                return ResourceManager.GetString("ORA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due date.
        /// </summary>
        public static string SCADENTA {
            get {
                return ResourceManager.GetString("SCADENTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deadline.
        /// </summary>
        public static string TERMEN {
            get {
                return ResourceManager.GetString("TERMEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrative deadline.
        /// </summary>
        public static string TERMEN_ADMINISTRATIV {
            get {
                return ResourceManager.GetString("TERMEN_ADMINISTRATIV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Court file stages.
        /// </summary>
        public static string TITLE {
            get {
                return ResourceManager.GetString("TITLE", resourceCulture);
            }
        }
    }
}
