//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace socisaV2.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SedintePortalResx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SedintePortalResx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("socisaV2.Resources.SedintePortalResx", typeof(SedintePortalResx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Court section.
        /// </summary>
        public static string COMPLET {
            get {
                return ResourceManager.GetString("COMPLET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string DATA {
            get {
                return ResourceManager.GetString("DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting date.
        /// </summary>
        public static string DATA_SEDINTA {
            get {
                return ResourceManager.GetString("DATA_SEDINTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File no..
        /// </summary>
        public static string DOSAR {
            get {
                return ResourceManager.GetString("DOSAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string ID_DOSAR {
            get {
                return ResourceManager.GetString("ID_DOSAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Court.
        /// </summary>
        public static string INSTANTA {
            get {
                return ResourceManager.GetString("INSTANTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring.
        /// </summary>
        public static string MONITORIZARE {
            get {
                return ResourceManager.GetString("MONITORIZARE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File no..
        /// </summary>
        public static string NR_DOSAR_CASCO {
            get {
                return ResourceManager.GetString("NR_DOSAR_CASCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Court file no..
        /// </summary>
        public static string NR_DOSAR_INSTANTA {
            get {
                return ResourceManager.GetString("NR_DOSAR_INSTANTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting hour.
        /// </summary>
        public static string ORA {
            get {
                return ResourceManager.GetString("ORA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Court file no..
        /// </summary>
        public static string PROCES {
            get {
                return ResourceManager.GetString("PROCES", resourceCulture);
            }
        }
    }
}
