//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace socisaV2.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SocietatiAsigurareResx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SocietatiAsigurareResx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("socisaV2.Resources.SocietatiAsigurareResx", typeof(SocietatiAsigurareResx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string ADRESA {
            get {
                return ResourceManager.GetString("ADRESA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank.
        /// </summary>
        public static string BANCA {
            get {
                return ResourceManager.GetString("BANCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CIF.
        /// </summary>
        public static string CUI {
            get {
                return ResourceManager.GetString("CUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last payment date.
        /// </summary>
        public static string DATA_ULTIMEI_PLATI {
            get {
                return ResourceManager.GetString("DATA_ULTIMEI_PLATI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string DENUMIRE {
            get {
                return ResourceManager.GetString("DENUMIRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short name.
        /// </summary>
        public static string DENUMIRE_SCURTA {
            get {
                return ResourceManager.GetString("DENUMIRE_SCURTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string DETALII {
            get {
                return ResourceManager.GetString("DETALII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string EMAIL {
            get {
                return ResourceManager.GetString("EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address confirmed.
        /// </summary>
        public static string EMAIL_CONFIRMAT {
            get {
                return ResourceManager.GetString("EMAIL_CONFIRMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications email address.
        /// </summary>
        public static string EMAIL_NOTIFICARI {
            get {
                return ResourceManager.GetString("EMAIL_NOTIFICARI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications email address confirmed.
        /// </summary>
        public static string EMAIL_NOTIFICARI_CONFIRMAT {
            get {
                return ResourceManager.GetString("EMAIL_NOTIFICARI_CONFIRMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBAN.
        /// </summary>
        public static string IBAN {
            get {
                return ResourceManager.GetString("IBAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications template.
        /// </summary>
        public static string ID_TEMPLATE_NOTIFICARI {
            get {
                return ResourceManager.GetString("ID_TEMPLATE_NOTIFICARI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry of Commerce no..
        /// </summary>
        public static string NR_REG_COM {
            get {
                return ResourceManager.GetString("NR_REG_COM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiscal representative.
        /// </summary>
        public static string REPREZENTANT_FISCAL {
            get {
                return ResourceManager.GetString("REPREZENTANT_FISCAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sold.
        /// </summary>
        public static string SOLD {
            get {
                return ResourceManager.GetString("SOLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string TELEFON {
            get {
                return ResourceManager.GetString("TELEFON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance companies.
        /// </summary>
        public static string TITLE {
            get {
                return ResourceManager.GetString("TITLE", resourceCulture);
            }
        }
    }
}
