//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace socisaV2.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StadiiResx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StadiiResx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("socisaV2.Resources.StadiiResx", typeof(StadiiResx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string CATEGORIE {
            get {
                return ResourceManager.GetString("CATEGORIE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string DENUMIRE {
            get {
                return ResourceManager.GetString("DENUMIRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string DETALII {
            get {
                return ResourceManager.GetString("DETALII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon path.
        /// </summary>
        public static string ICON_PATH {
            get {
                return ResourceManager.GetString("ICON_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group/Category.
        /// </summary>
        public static string PARENT_ID {
            get {
                return ResourceManager.GetString("PARENT_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string PAS {
            get {
                return ResourceManager.GetString("PAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sentence stage.
        /// </summary>
        public static string STADIU_CU_SENTINTA {
            get {
                return ResourceManager.GetString("STADIU_CU_SENTINTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deadline stage.
        /// </summary>
        public static string STADIU_CU_TERMEN {
            get {
                return ResourceManager.GetString("STADIU_CU_TERMEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Court stage.
        /// </summary>
        public static string STADIU_INSTANTA {
            get {
                return ResourceManager.GetString("STADIU_INSTANTA", resourceCulture);
            }
        }
    }
}
