//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace socisaV2.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TipDocumenteResx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TipDocumenteResx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("socisaV2.Resources.TipDocumenteResx", typeof(TipDocumenteResx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTHER DOCUMENTS.
        /// </summary>
        public static string ALTE_INSCRISURI {
            get {
                return ResourceManager.GetString("ALTE_INSCRISURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOSS POLICY ACCEPTANCE.
        /// </summary>
        public static string AVIZARE_DE_DAUNE_POLITA_PAGUBIT {
            get {
                return ResourceManager.GetString("AVIZARE_DE_DAUNE_POLITA_PAGUBIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VMD CALCULATION.
        /// </summary>
        public static string CALCUL_VMD {
            get {
                return ResourceManager.GetString("CALCUL_VMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEDAM.
        /// </summary>
        public static string CEDAM {
            get {
                return ResourceManager.GetString("CEDAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOSS COMPENSATION REQUEST.
        /// </summary>
        public static string CERERE_DE_DESPAGUBIRE_AUTO_PAGUBIT {
            get {
                return ResourceManager.GetString("CERERE_DE_DESPAGUBIRE_AUTO_PAGUBIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOSS MATRICULATION CERTIFICATE.
        /// </summary>
        public static string CERTIFICAT_DE_INMATRICULARE_PAGUBIT {
            get {
                return ResourceManager.GetString("CERTIFICAT_DE_INMATRICULARE_PAGUBIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GUILTY MATRICULATION CERTIFICATE.
        /// </summary>
        public static string CERTIFICAT_DE_INMATRICULARE_VINOVAT {
            get {
                return ResourceManager.GetString("CERTIFICAT_DE_INMATRICULARE_VINOVAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOSS COMPENSATION REQUEST CONFIRMATION.
        /// </summary>
        public static string CONFIRMARE_CERERE_DESPAGUBIRE {
            get {
                return ResourceManager.GetString("CONFIRMARE_CERERE_DESPAGUBIRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MUTUAL AGREEMENT.
        /// </summary>
        public static string CONSTATARE_AMIABILA {
            get {
                return ResourceManager.GetString("CONSTATARE_AMIABILA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REPAIR DEVICE.
        /// </summary>
        public static string DEVIZ_DE_REPARATII {
            get {
                return ResourceManager.GetString("DEVIZ_DE_REPARATII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INDEMNITY PAYMENT PROOFS.
        /// </summary>
        public static string DOVEZI_DE_PLATA_A_INDEMNIZATIEI {
            get {
                return ResourceManager.GetString("DOVEZI_DE_PLATA_A_INDEMNIZATIEI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REPAIR INVOICE.
        /// </summary>
        public static string FACTURA_DE_REPARATII {
            get {
                return ResourceManager.GetString("FACTURA_DE_REPARATII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASCERTAINMENT PICTURES.
        /// </summary>
        public static string FOTOGRAFII_DE_CONSTATARE {
            get {
                return ResourceManager.GetString("FOTOGRAFII_DE_CONSTATARE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POWER OF ATTORNEY.
        /// </summary>
        public static string IMPUTERNICIRE {
            get {
                return ResourceManager.GetString("IMPUTERNICIRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASCERTAINMENT NOTE.
        /// </summary>
        public static string NOTA_DE_CONSTATARE {
            get {
                return ResourceManager.GetString("NOTA_DE_CONSTATARE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REASCERTAINMENT NOTE.
        /// </summary>
        public static string NOTA_DE_RECONSTATARE {
            get {
                return ResourceManager.GetString("NOTA_DE_RECONSTATARE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOSS POLICY.
        /// </summary>
        public static string POLITA_PAGUBIT {
            get {
                return ResourceManager.GetString("POLITA_PAGUBIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GUILTY POLICY.
        /// </summary>
        public static string POLITA_VINOVAT {
            get {
                return ResourceManager.GetString("POLITA_VINOVAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MINUTES.
        /// </summary>
        public static string PROCES_VERBAL {
            get {
                return ResourceManager.GetString("PROCES_VERBAL", resourceCulture);
            }
        }
    }
}
